### ISSUE TITLE
Unicode support in address lines

### ISSUE THREAD

**Issue by ChristianHopper** [cole/aiosmtplib#120]
I've looked around in the tests for examples on how to properly send mails with non-ascii characters in address lines. I cannot get the following to work:

```
import asyncio
from email.message import EmailMessage
from aiosmtplib.email import formataddr

import aiosmtplib

PASSWORD = 'password'
USER = 'user@example.com'


async def send_hello_world():
    message = EmailMessage()
    message["From"] = "user@example.com"
    message["To"] = formataddr(("æøå", "someotheruser@example.com"))
    message["Subject"] = "Hello World!"
    message.set_content("Sent via aiosmtplib")

    send = await aiosmtplib.send(message,
                          hostname="smtp.office365.com",
                          port=587,
                        start_tls=True,
                          password=PASSWORD,
                          username=USER)
    return send

event_loop = asyncio.get_event_loop()
event_loop.run_until_complete(send_hello_world())
```
The interesting line is this: `message["To"] = formataddr(("æøå", "someotheruser@example.com"))`. The`æøå` breaks the email somehow.

I do receive an email - however, there is no subject and the email body is the EmailMessage sort of converted to a string. I could succesfully send the email with smtplib with no issues. What do I nee

**Comment by ChristianHopper** [comment]
Fixed by upgrading to python 3.7

**Comment by cole** [comment]
If this is happening on 3.5/3.6 it's still an issue — I just haven't had a chance to look into it yet.

**Comment by ChristianHopper** [comment]
Noted, thanks for taking the time to create this wonderful library

**Comment by cole** [comment]
I can't reproduce this; I've added a test case for it though, I think that should cover it.
